#!/usr/bin/env bash
# Map devto-aha-* articles to existing cover JPEGs (>=20KB).
set -euo pipefail
D=/home/moshe/work/kiponos-io/docs
cp "$D/devto-cover-arch-resilience.jpg" "$D/devto-cover-aha-circuit-breaker-threshold.jpg"
cp "$D/devto-cover-ci-testing.jpg" "$D/devto-cover-aha-scheduled-fixed-delay.jpg"
cp "$D/devto-cover-rate-limits.jpg" "$D/devto-cover-aha-pagination-page-size.jpg"
cp "$D/devto-cover-saas.jpg" "$D/devto-cover-aha-session-timeout.jpg"
cp "$D/devto-cover-microservices-events.jpg" "$D/devto-cover-aha-kafka-max-poll.jpg"
cp "$D/devto-cover-arch-resilience.jpg" "$D/devto-cover-aha-bulkhead-concurrent.jpg"
cp "$D/devto-cover-arch-pools.jpg" "$D/devto-cover-aha-hikari-pool-max.jpg"
cp "$D/devto-cover-automation-no-env.jpg" "$D/devto-cover-aha-python-semaphore.jpg"
cp "$D/devto-cover-k8s-no-restart.jpg" "$D/devto-cover-aha-graceful-shutdown.jpg"
cp "$D/devto-cover-waf.jpg" "$D/devto-cover-aha-jwt-leeway.jpg"
cp "$D/devto-cover-rate-limits.jpg" "$D/devto-cover-aha-upload-max-size.jpg"
cp "$D/devto-cover-arch-resilience.jpg" "$D/devto-cover-aha-circuit-wait-open.jpg"
cp "$D/devto-cover-supervisor-ml.jpg" "$D/devto-cover-aha-python-pool-workers.jpg"
cp "$D/devto-cover-llm-serving.jpg" "$D/devto-cover-aha-debounce-ms.jpg"
cp "$D/devto-cover-arch-canary.jpg" "$D/devto-cover-aha-canary-percent.jpg"
cp "$D/devto-cover-arch-observability.jpg" "$D/devto-cover-aha-health-poll-interval.jpg"
cp "$D/devto-cover-accounting-close.jpg" "$D/devto-cover-aha-sql-query-limit.jpg"
cp "$D/devto-cover-arch-pools.jpg" "$D/devto-cover-aha-executor-queue-capacity.jpg"
cp "$D/devto-cover-automation-no-env.jpg" "$D/devto-cover-aha-python-request-timeout.jpg"
cp "$D/devto-cover-fraud-routing.jpg" "$D/devto-cover-aha-idempotency-window.jpg"
cp "$D/devto-cover-staging-profile.jpg" "$D/devto-cover-aha-warmup-traffic.jpg"
cp "$D/devto-cover-energy.jpg" "$D/devto-cover-aha-shed-load-threshold.jpg"
cp "$D/devto-cover-ci-testing.jpg" "$D/devto-cover-aha-python-worker-concurrency.jpg"
cp "$D/devto-cover-cdn.jpg" "$D/devto-cover-aha-cors-max-age.jpg"
echo "Covers ready: $(ls -1 "$D"/devto-cover-aha-*.jpg | wc -l) files"